import type { Metadata } from "next";
import { Comfortaa, Ibarra_Real_Nova } from "next/font/google";
import "./globals.css";

const ibarra = Ibarra_Real_Nova({
  variable: "--font-ibarra",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const comfortaa = Comfortaa({
  weight: ['300', '400', '500', '600', '700'],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibarra.variable} ${comfortaa.className} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
